### ISSUE TITLE
[13.0] [BUG]"github_connector" module > Wrong hierarchical structure of directory path arborescence & Github URL field, on "github.repository.branch" form view

### ISSUE THREAD

**Issue by NCS-75** [OCA/interface-git#52]
**Context :**
OCB 13.0 Odoo Server up to date [(07/06/2020),] 
Not able to reproduce on runbot : http://3430035-13-0-523584.runbot2.odoo-community.org, because of mising setting possibility :  github_login' and 'github_password' in Odoo configuration file

**Steps to reproduce :**
Install "github_connector" module
Apply extra settings to mention Github credentials, in odoo conf file
- ;""GITHUB Connector credentials""
- source_code_local_path = /opt/odoo/odoo_v13/source_code/
- github_login = your_github_login
- github_password = your_github_password

Go to ‘Settings’ / ‘Technical’ / ‘Parameters’ / ‘System Parameters’ and define the required values
Go to your(s) user(s) form to add them in the new ‘Connector Github Manager’ groups
Go to ‘Github’ / ‘Settings’ / ‘Sync Object’, and select the object type you want to synchronize and its Gthub name (OCA, or muk-it) ; then click to "Load from Github"
Once done for your organization(s), go to ‘Github’ / ‘Github Commnunity’ / ‘Organizations’ and, click on your organization / ‘Organization Series’ Tabs, to set repositories you don’t want to download (or repositories you want to download). Also, click to "Repositories sync"
Now, you suppose to see on the form, the count button repositories link incremented. 

>>>**_Then, access to the form of any branches created, by going from menu to "Github repository/Repository branches" and look at the **wrong syntax displayed , on ""Github_url"" field** :_** 

_(model=github.repository.branch&view_type=form)_
Github URL : | https://github.com/OCA/OCA/account-invoicing/tree/13.0 
--|--

Same for another banch,
Github URL : | https://github.com/muk-it/muk-it/muk_base/tree/13.0 
--|--

**Mistake ? :** 
(/models/github_repository_branch.py)
Code suppose to display right url syntax, no ?
```python
@api.depends("name", "repository_id.complete_name")
    def _compute_github_url(self):
        for branch in self:
            branch.github_url = "https://github.com/{}/{}/tree/{}".format(
                branch.organization_id.github_login,
                branch.repository_id.complete_name,
                branch.name,
            )
...
github_url = fields.Char(
        string="Github URL", store=True, compute="_compute_github_url"
```
.
_(/views/view_github_repository_branch.xml)_
Line 174 : `<field name="github_url" widget="url" colspan="4" />`

**Consequence:**
Github url link not rechable,
Directory, on server, are also created base on same **wrong** arborescence : 

- /opt/odoo/odoo_v13/source_code/OCA/OCA/account-invoicing/
- /opt/odoo/odoo_v13/source_code/muk-it/muk-it/muk_base/
-----
@cristinamartinrod 
@cubells 
@StephanRozendaal 
@ernestotejeda 
Is there anything i didn't figure out ?
.
**Downside images** :
/opt/odoo/odoo_v13/source_code/  , and subdirectories created by the module, based on odoo conf file extra settings : source_code_local_path = /opt/odoo/odoo_v13/source_code/
![Connector2](https://user-images.githubusercontent.com/59052920/86791002-58139980-c069-11ea-89c9-98fba1f468cb.JPG)
![Connector1](https://user-images.githubusercontent.com/59052920/86793163-7b3f4880-c06b-11ea-902a-20edd1202d60.JPG)

**Comment by pedrobaeza** [comment]
Fixed in 6cc412a64b33a4969948efdb93691d933c105e91

**Comment by NCS-75** [comment]
Hi,
@pedrobaeza 
Thanks for the fix 6cc412a

Under your control, It seems that you forgot to modify also this part of code on "github_repository_branch.py" line 279
)

```python
    # Compute Section
    @api.depends("name", "repository_id.name")
    def _compute_complete_name(self):
        for branch in self:
            branch.complete_name = (
# -              branch.repository_id.complete_name + "/" + branch.name
                 branch.repository_id.name + "/" + branch.name
            )


```
.
If you do so, directory arborescence is ok, then.... (like downside image)
![Connector3](https://user-images.githubusercontent.com/59052920/86848949-3e954080-c0af-11ea-946a-2cf3190ebf07.JPG)

**Comment by pedrobaeza** [comment]
OK, fixed in a4cdbdc1d4ef02ebcf099270fe5218f80e6a9390. Next time, you can do the PR with the needed changes if you prefer.
